service: ivent-serverless-app-dev
frameworkVersion: '3'

custom:
  dogsTableName: 'dogs-table-${sls:stage}'
  dogApiUrl: https://dog.ceo/api

provider:
  name: aws
  region: eu-west-1
  stage: dev
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - cognito-idp:*
          Resource:
            - Fn::GetAtt: [ DogsTable, Arn ]
            - Fn::GetAtt: [ UserPool, Arn ]
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: 
          Fn::Join:
          - ''
          - - 'https://cognito-idp.'
            - '${opt:region, self:provider.region}'
            - '.amazonaws.com/'
            - Ref: UserPool
        audience:
          - Ref: UserClient

  environment:
    DogsTable: ${self:custom.dogsTableName}
    USER_POOL: 
      Ref: UserPool
    USER_CLIENT:
      Ref: UserClient
    SERVICE_REGION: ${aws:region}
    DOG_API: ${self:custom.dogApiUrl}

functions:
  httpApi:
    handler: index.handler
    middleware:
      pre:
        - src/middlewares/auth.authMiddleware
    events:
      - httpApi:
          method: '*'
          path: /{proxy+}
          authorizer: jwtAuthorizer

  signUpUser:
    handler: src/controllers/public/auth.signUpUser
    events:
      - httpApi:
            method: POST
            path: /auth/signup
  signInUser:
    handler: src/controllers/public/auth.signInUser
    events:
      - httpApi:
            method: POST
            path: /auth/signin

resources:
  Resources:
    DogsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: identifier
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: identifier
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.dogsTableName}
    
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ivent-auth-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: name
            Required: true
            Mutable: true
          - Name: family_name
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"]

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ivent-pool-client
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"
          - "USER_PASSWORD_AUTH"

plugins:
  - serverless-middleware
